language: node_js
node_js:
  # https://github.com/nodejs/LTS
  # - "6" # ends April 2019
  - "8" # ends December 2019
  # - "10" # ends April 2021

sudo: required

services:
  - docker

script:
  - yarn install
  - yarn ci
  - if [[ $TRAVIS_REPO_SLUG == "Zilliqa/zdex-app" && $TRAVIS_BRANCH = "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
      yarn build;
      yarn global add firebase-tools typescript tslint;
      firebase use production;
      firebase deploy --token $FIREBASE_TOKEN --non-interactive;
    fi

after_success:
  - if [[ $TRAVIS_REPO_SLUG == "Zilliqa/zdex-app" && $TRAVIS_BRANCH = "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
      docker --version;
      pip install --user awscli;
      export PATH=$PATH:$HOME/.local/bin;
      account_id=$(aws sts get-caller-identity --output text --query 'Account');
      region_id=us-west-2;
      registry_url=${account_id}.dkr.ecr.${region_id}.amazonaws.com/wallet;
      eval $(aws ecr get-login --no-include-email --region ${region_id});
      docker build -t ${registry_url} .;
      docker push ${registry_url};
      npm run deploy-storybook -- --ci;
    fi
